name = "BiweightStats"
uuid = "5bf8a1e9-d5f8-4697-9608-80edd97af0ad"
authors = ["Miles Lucas <mdlucas@hawaii.edu> and contributors"]
version = "1.0.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.6"
